# Generated by Django 5.1.6 on 2025-03-07 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('academicYearID', models.AutoField(primary_key=True, serialize=False)),
                ('academicYearFrom', models.DateField()),
                ('academicYearTo', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campusID', models.AutoField(primary_key=True, serialize=False)),
                ('campusName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('departmentID', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('educationLevelD', models.AutoField(primary_key=True, serialize=False)),
                ('levelName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('facultyID', models.AutoField(primary_key=True, serialize=False)),
                ('facultyName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semesterID', models.AutoField(primary_key=True, serialize=False)),
                ('semesterName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampusDepartment',
            fields=[
                ('campusdepartID', models.AutoField(primary_key=True, serialize=False)),
                ('HOD', models.ForeignKey(limit_choices_to={'groups__name': 'Staff'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.campus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.faculty'),
        ),
        migrations.CreateModel(
            name='Programmes',
            fields=[
                ('programmesID', models.AutoField(primary_key=True, serialize=False)),
                ('programmeName', models.CharField(max_length=150, unique=True)),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.educationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSemester',
            fields=[
                ('scheduleSemesterID', models.AutoField(primary_key=True, serialize=False)),
                ('semesterFrom', models.DateField()),
                ('semesterTo', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('academicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.academicyear')),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.educationlevel')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('examID', models.AutoField(primary_key=True, serialize=False)),
                ('examStartFrom', models.DateField()),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.educationlevel')),
                ('scheduleSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.schedulesemester')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseID', models.AutoField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=150, unique=True)),
                ('courseCode', models.CharField(max_length=6, unique=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.semester')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrationNumber', models.CharField(max_length=15, unique=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.campus')),
                ('educationLevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.educationlevel')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.programmes')),
                ('user', models.ForeignKey(limit_choices_to={'groups__name': 'Student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cw', models.CharField(max_length=3)),
                ('ue', models.CharField(max_length=3)),
                ('scheduleSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.schedulesemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.student')),
            ],
        ),
        migrations.CreateModel(
            name='Postponement',
            fields=[
                ('postponementID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='In progress', max_length=15)),
                ('activity', models.CharField(max_length=50)),
                ('requested', models.DateField(auto_now_add=True)),
                ('msg', models.TextField(null=True)),
                ('reason', models.CharField(max_length=30)),
                ('evidence', models.FileField(max_length=255, upload_to='evidence/')),
                ('academicYear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.academicyear')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.campus')),
                ('scheduleSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.schedulesemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('studentCourseID', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.course')),
                ('scheduleSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.schedulesemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.student')),
            ],
        ),
        migrations.CreateModel(
            name='PostponedExam',
            fields=[
                ('postponedExamID', models.AutoField(primary_key=True, serialize=False)),
                ('postponement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.postponement')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.studentcourse')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('studentRegistrationID', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleSemester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.schedulesemester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.student')),
            ],
        ),
    ]
