# Generated by Django 5.1.6 on 2025-03-12 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponement',
            name='expire',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResumeStudies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumed', models.DateField(auto_created=True)),
                ('attachement', models.FileField(max_length=255, upload_to='resume/')),
                ('Postponement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postponement.postponement')),
            ],
        ),
    ]
