# Generated by Django 5.1.6 on 2025-03-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0002_postponement_expire_resumestudies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponement',
            name='expire',
            field=models.DateField(null=True),
        ),
    ]
