# Generated by Django 5.1.6 on 2025-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0003_alter_postponement_expire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumestudies',
            old_name='Postponement',
            new_name='postponement',
        ),
    ]
