# Generated by Django 5.1.6 on 2025-03-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0004_rename_postponement_resumestudies_postponement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumestudies',
            name='resumed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
