# Generated by Django 5.1.6 on 2025-03-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0005_alter_resumestudies_resumed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumestudies',
            name='postponement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postponement.postponement'),
        ),
    ]
