# Generated by Django 5.1.6 on 2025-03-17 07:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0006_alter_resumestudies_postponement'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumestudies',
            name='resume_requested',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumestudies',
            name='resume_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
