# Generated by Django 5.1.6 on 2025-03-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postponement', '0007_resumestudies_resume_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponement',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
